#include <achain/protocol/get_config.hpp>
#include <achain/protocol/config.hpp>
#include <achain/protocol/asset.hpp>
#include <achain/protocol/types.hpp>
#include <achain/protocol/version.hpp>

namespace achain { namespace protocol {

fc::variant_object get_config()
{
   fc::mutable_variant_object result;

#ifdef IS_TEST_NET
   result[ "IS_TEST_NET" ] = true;
#else
   result[ "IS_TEST_NET" ] = false;
#endif

   result["SBD_SYMBOL"] = SBD_SYMBOL;
   result["ACHAIN_100_PERCENT"] = ACHAIN_100_PERCENT;
   result["ACHAIN_1_PERCENT"] = ACHAIN_1_PERCENT;
   result["ACHAIN_1_TENTH_PERCENT"] = ACHAIN_1_TENTH_PERCENT;
   result["ACHAIN_ACCOUNT_RECOVERY_REQUEST_EXPIRATION_PERIOD"] = ACHAIN_ACCOUNT_RECOVERY_REQUEST_EXPIRATION_PERIOD;
   result["ACHAIN_ACTIVE_CHALLENGE_COOLDOWN"] = ACHAIN_ACTIVE_CHALLENGE_COOLDOWN;
   result["ACHAIN_ACTIVE_CHALLENGE_FEE"] = ACHAIN_ACTIVE_CHALLENGE_FEE;
   result["ACHAIN_ADDRESS_PREFIX"] = ACHAIN_ADDRESS_PREFIX;
   result["ACHAIN_APR_PERCENT_MULTIPLY_PER_BLOCK"] = ACHAIN_APR_PERCENT_MULTIPLY_PER_BLOCK;
   result["ACHAIN_APR_PERCENT_MULTIPLY_PER_HOUR"] = ACHAIN_APR_PERCENT_MULTIPLY_PER_HOUR;
   result["ACHAIN_APR_PERCENT_MULTIPLY_PER_ROUND"] = ACHAIN_APR_PERCENT_MULTIPLY_PER_ROUND;
   result["ACHAIN_APR_PERCENT_SHIFT_PER_BLOCK"] = ACHAIN_APR_PERCENT_SHIFT_PER_BLOCK;
   result["ACHAIN_APR_PERCENT_SHIFT_PER_HOUR"] = ACHAIN_APR_PERCENT_SHIFT_PER_HOUR;
   result["ACHAIN_APR_PERCENT_SHIFT_PER_ROUND"] = ACHAIN_APR_PERCENT_SHIFT_PER_ROUND;
   result["ACHAIN_BANDWIDTH_AVERAGE_WINDOW_SECONDS"] = ACHAIN_BANDWIDTH_AVERAGE_WINDOW_SECONDS;
   result["ACHAIN_BANDWIDTH_PRECISION"] = ACHAIN_BANDWIDTH_PRECISION;
   result["ACHAIN_BLOCKCHAIN_PRECISION"] = ACHAIN_BLOCKCHAIN_PRECISION;
   result["ACHAIN_BLOCKCHAIN_PRECISION_DIGITS"] = ACHAIN_BLOCKCHAIN_PRECISION_DIGITS;
   result["ACHAIN_BLOCKCHAIN_HARDFORK_VERSION"] = ACHAIN_BLOCKCHAIN_HARDFORK_VERSION;
   result["ACHAIN_BLOCKCHAIN_VERSION"] = ACHAIN_BLOCKCHAIN_VERSION;
   result["ACHAIN_BLOCK_INTERVAL"] = ACHAIN_BLOCK_INTERVAL;
   result["ACHAIN_BLOCKS_PER_DAY"] = ACHAIN_BLOCKS_PER_DAY;
   result["ACHAIN_BLOCKS_PER_HOUR"] = ACHAIN_BLOCKS_PER_HOUR;
   result["ACHAIN_BLOCKS_PER_YEAR"] = ACHAIN_BLOCKS_PER_YEAR;
   result["ACHAIN_CASHOUT_WINDOW_SECONDS"] = ACHAIN_CASHOUT_WINDOW_SECONDS;
   result["ACHAIN_CASHOUT_WINDOW_SECONDS_PRE_HF12"] = ACHAIN_CASHOUT_WINDOW_SECONDS_PRE_HF12;
   result["ACHAIN_CASHOUT_WINDOW_SECONDS_PRE_HF17"] = ACHAIN_CASHOUT_WINDOW_SECONDS_PRE_HF17;
   result["ACHAIN_CHAIN_ID"] = ACHAIN_CHAIN_ID;
   result["ACHAIN_COMMENT_REWARD_FUND_NAME"] = ACHAIN_COMMENT_REWARD_FUND_NAME;
   result["ACHAIN_CONTENT_APR_PERCENT"] = ACHAIN_CONTENT_APR_PERCENT;
   result["ACHAIN_CONTENT_CONSTANT_HF0"] = ACHAIN_CONTENT_CONSTANT_HF0;
   result["ACHAIN_CONTENT_REWARD_PERCENT"] = ACHAIN_CONTENT_REWARD_PERCENT;
   result["ACHAIN_CONVERSION_DELAY"] = ACHAIN_CONVERSION_DELAY;
   result["ACHAIN_CONVERSION_DELAY_PRE_HF_16"] = ACHAIN_CONVERSION_DELAY_PRE_HF_16;
   result["ACHAIN_CREATE_ACCOUNT_DELEGATION_RATIO"] = ACHAIN_CREATE_ACCOUNT_DELEGATION_RATIO;
   result["ACHAIN_CREATE_ACCOUNT_DELEGATION_TIME"] = ACHAIN_CREATE_ACCOUNT_DELEGATION_TIME;
   result["ACHAIN_CREATE_ACCOUNT_WITH_STEEM_MODIFIER"] = ACHAIN_CREATE_ACCOUNT_WITH_STEEM_MODIFIER;
   result["ACHAIN_CURATE_APR_PERCENT"] = ACHAIN_CURATE_APR_PERCENT;
   result["ACHAIN_DEFAULT_SBD_INTEREST_RATE"] = ACHAIN_DEFAULT_SBD_INTEREST_RATE;
   result["ACHAIN_EQUIHASH_K"] = ACHAIN_EQUIHASH_K;
   result["ACHAIN_EQUIHASH_N"] = ACHAIN_EQUIHASH_N;
   result["ACHAIN_FEED_HISTORY_WINDOW"] = ACHAIN_FEED_HISTORY_WINDOW;
   result["ACHAIN_FEED_HISTORY_WINDOW_PRE_HF_16"] = ACHAIN_FEED_HISTORY_WINDOW_PRE_HF_16;
   result["ACHAIN_FEED_INTERVAL_BLOCKS"] = ACHAIN_FEED_INTERVAL_BLOCKS;
   result["ACHAIN_FREE_TRANSACTIONS_WITH_NEW_ACCOUNT"] = ACHAIN_FREE_TRANSACTIONS_WITH_NEW_ACCOUNT;
   result["ACHAIN_GENESIS_TIME"] = ACHAIN_GENESIS_TIME;
   result["ACHAIN_HARDFORK_REQUIRED_WITNESSES"] = ACHAIN_HARDFORK_REQUIRED_WITNESSES;
   result["ACHAIN_INFLATION_NARROWING_PERIOD"] = ACHAIN_INFLATION_NARROWING_PERIOD;
   result["ACHAIN_INFLATION_RATE_START_PERCENT"] = ACHAIN_INFLATION_RATE_START_PERCENT;
   result["ACHAIN_INFLATION_RATE_STOP_PERCENT"] = ACHAIN_INFLATION_RATE_STOP_PERCENT;
   result["ACHAIN_INIT_MINER_NAME"] = ACHAIN_INIT_MINER_NAME;
   result["ACHAIN_INIT_PUBLIC_KEY_STR"] = ACHAIN_INIT_PUBLIC_KEY_STR;
#if 0
   // do not expose private key, period.
   // we need this line present but inactivated so CI check for all constants in config.hpp doesn't complain.
   result["ACHAIN_INIT_PRIVATE_KEY"] = ACHAIN_INIT_PRIVATE_KEY;
#endif
   result["ACHAIN_INIT_SUPPLY"] = ACHAIN_INIT_SUPPLY;
   result["ACHAIN_INIT_TIME"] = ACHAIN_INIT_TIME;
   result["ACHAIN_IRREVERSIBLE_THRESHOLD"] = ACHAIN_IRREVERSIBLE_THRESHOLD;
   result["ACHAIN_LIQUIDITY_APR_PERCENT"] = ACHAIN_LIQUIDITY_APR_PERCENT;
   result["ACHAIN_LIQUIDITY_REWARD_BLOCKS"] = ACHAIN_LIQUIDITY_REWARD_BLOCKS;
   result["ACHAIN_LIQUIDITY_REWARD_PERIOD_SEC"] = ACHAIN_LIQUIDITY_REWARD_PERIOD_SEC;
   result["ACHAIN_LIQUIDITY_TIMEOUT_SEC"] = ACHAIN_LIQUIDITY_TIMEOUT_SEC;
   result["ACHAIN_MAX_ACCOUNT_NAME_LENGTH"] = ACHAIN_MAX_ACCOUNT_NAME_LENGTH;
   result["ACHAIN_MAX_ACCOUNT_WITNESS_VOTES"] = ACHAIN_MAX_ACCOUNT_WITNESS_VOTES;
   result["ACHAIN_MAX_ASSET_WHITELIST_AUTHORITIES"] = ACHAIN_MAX_ASSET_WHITELIST_AUTHORITIES;
   result["ACHAIN_MAX_AUTHORITY_MEMBERSHIP"] = ACHAIN_MAX_AUTHORITY_MEMBERSHIP;
   result["ACHAIN_MAX_BLOCK_SIZE"] = ACHAIN_MAX_BLOCK_SIZE;
   result["ACHAIN_SOFT_MAX_BLOCK_SIZE"] = ACHAIN_SOFT_MAX_BLOCK_SIZE;
   result["ACHAIN_MAX_CASHOUT_WINDOW_SECONDS"] = ACHAIN_MAX_CASHOUT_WINDOW_SECONDS;
   result["ACHAIN_MAX_COMMENT_DEPTH"] = ACHAIN_MAX_COMMENT_DEPTH;
   result["ACHAIN_MAX_COMMENT_DEPTH_PRE_HF17"] = ACHAIN_MAX_COMMENT_DEPTH_PRE_HF17;
   result["ACHAIN_MAX_FEED_AGE_SECONDS"] = ACHAIN_MAX_FEED_AGE_SECONDS;
   result["ACHAIN_MAX_INSTANCE_ID"] = ACHAIN_MAX_INSTANCE_ID;
   result["ACHAIN_MAX_MEMO_SIZE"] = ACHAIN_MAX_MEMO_SIZE;
   result["ACHAIN_MAX_WITNESSES"] = ACHAIN_MAX_WITNESSES;
   result["ACHAIN_MAX_MINER_WITNESSES_HF0"] = ACHAIN_MAX_MINER_WITNESSES_HF0;
   result["ACHAIN_MAX_MINER_WITNESSES_HF17"] = ACHAIN_MAX_MINER_WITNESSES_HF17;
   result["ACHAIN_MAX_PERMLINK_LENGTH"] = ACHAIN_MAX_PERMLINK_LENGTH;
   result["ACHAIN_MAX_PROXY_RECURSION_DEPTH"] = ACHAIN_MAX_PROXY_RECURSION_DEPTH;
   result["ACHAIN_MAX_RATION_DECAY_RATE"] = ACHAIN_MAX_RATION_DECAY_RATE;
   result["ACHAIN_MAX_RESERVE_RATIO"] = ACHAIN_MAX_RESERVE_RATIO;
   result["ACHAIN_MAX_RUNNER_WITNESSES_HF0"] = ACHAIN_MAX_RUNNER_WITNESSES_HF0;
   result["ACHAIN_MAX_RUNNER_WITNESSES_HF17"] = ACHAIN_MAX_RUNNER_WITNESSES_HF17;
   result["ACHAIN_MAX_SHARE_SUPPLY"] = ACHAIN_MAX_SHARE_SUPPLY;
   result["ACHAIN_MAX_SIG_CHECK_DEPTH"] = ACHAIN_MAX_SIG_CHECK_DEPTH;
   result["ACHAIN_MAX_TIME_UNTIL_EXPIRATION"] = ACHAIN_MAX_TIME_UNTIL_EXPIRATION;
   result["ACHAIN_MAX_TRANSACTION_SIZE"] = ACHAIN_MAX_TRANSACTION_SIZE;
   result["ACHAIN_MAX_UNDO_HISTORY"] = ACHAIN_MAX_UNDO_HISTORY;
   result["ACHAIN_MAX_URL_LENGTH"] = ACHAIN_MAX_URL_LENGTH;
   result["ACHAIN_MAX_VOTE_CHANGES"] = ACHAIN_MAX_VOTE_CHANGES;
   result["ACHAIN_MAX_VOTED_WITNESSES_HF0"] = ACHAIN_MAX_VOTED_WITNESSES_HF0;
   result["ACHAIN_MAX_VOTED_WITNESSES_HF17"] = ACHAIN_MAX_VOTED_WITNESSES_HF17;
   result["ACHAIN_MAX_WITHDRAW_ROUTES"] = ACHAIN_MAX_WITHDRAW_ROUTES;
   result["ACHAIN_MAX_WITNESS_URL_LENGTH"] = ACHAIN_MAX_WITNESS_URL_LENGTH;
   result["ACHAIN_MIN_ACCOUNT_CREATION_FEE"] = ACHAIN_MIN_ACCOUNT_CREATION_FEE;
   result["ACHAIN_MIN_ACCOUNT_NAME_LENGTH"] = ACHAIN_MIN_ACCOUNT_NAME_LENGTH;
   result["ACHAIN_MIN_BLOCK_SIZE"] = ACHAIN_MIN_BLOCK_SIZE;
   result["ACHAIN_MIN_BLOCK_SIZE_LIMIT"] = ACHAIN_MIN_BLOCK_SIZE_LIMIT;
   result["ACHAIN_MIN_CONTENT_REWARD"] = ACHAIN_MIN_CONTENT_REWARD;
   result["ACHAIN_MIN_CURATE_REWARD"] = ACHAIN_MIN_CURATE_REWARD;
   result["ACHAIN_MIN_PERMLINK_LENGTH"] = ACHAIN_MIN_PERMLINK_LENGTH;
   result["ACHAIN_MIN_REPLY_INTERVAL"] = ACHAIN_MIN_REPLY_INTERVAL;
   result["ACHAIN_MIN_ROOT_COMMENT_INTERVAL"] = ACHAIN_MIN_ROOT_COMMENT_INTERVAL;
   result["ACHAIN_MIN_VOTE_INTERVAL_SEC"] = ACHAIN_MIN_VOTE_INTERVAL_SEC;
   result["ACHAIN_MINER_ACCOUNT"] = ACHAIN_MINER_ACCOUNT;
   result["ACHAIN_MINER_PAY_PERCENT"] = ACHAIN_MINER_PAY_PERCENT;
   result["ACHAIN_MIN_FEEDS"] = ACHAIN_MIN_FEEDS;
   result["ACHAIN_MINING_REWARD"] = ACHAIN_MINING_REWARD;
   result["ACHAIN_MINING_TIME"] = ACHAIN_MINING_TIME;
   result["ACHAIN_MIN_LIQUIDITY_REWARD"] = ACHAIN_MIN_LIQUIDITY_REWARD;
   result["ACHAIN_MIN_LIQUIDITY_REWARD_PERIOD_SEC"] = ACHAIN_MIN_LIQUIDITY_REWARD_PERIOD_SEC;
   result["ACHAIN_MIN_PAYOUT_SBD"] = ACHAIN_MIN_PAYOUT_SBD;
   result["ACHAIN_MIN_POW_REWARD"] = ACHAIN_MIN_POW_REWARD;
   result["ACHAIN_MIN_PRODUCER_REWARD"] = ACHAIN_MIN_PRODUCER_REWARD;
   result["ACHAIN_MIN_RATION"] = ACHAIN_MIN_RATION;
   result["ACHAIN_MIN_TRANSACTION_EXPIRATION_LIMIT"] = ACHAIN_MIN_TRANSACTION_EXPIRATION_LIMIT;
   result["ACHAIN_MIN_TRANSACTION_SIZE_LIMIT"] = ACHAIN_MIN_TRANSACTION_SIZE_LIMIT;
   result["ACHAIN_MIN_UNDO_HISTORY"] = ACHAIN_MIN_UNDO_HISTORY;
   result["ACHAIN_NULL_ACCOUNT"] = ACHAIN_NULL_ACCOUNT;
   result["ACHAIN_NUM_INIT_MINERS"] = ACHAIN_NUM_INIT_MINERS;
   result["ACHAIN_ORIGINAL_MIN_ACCOUNT_CREATION_FEE"] = ACHAIN_ORIGINAL_MIN_ACCOUNT_CREATION_FEE;
   result["ACHAIN_OWNER_AUTH_HISTORY_TRACKING_START_BLOCK_NUM"] = ACHAIN_OWNER_AUTH_HISTORY_TRACKING_START_BLOCK_NUM;
   result["ACHAIN_OWNER_AUTH_RECOVERY_PERIOD"] = ACHAIN_OWNER_AUTH_RECOVERY_PERIOD;
   result["ACHAIN_OWNER_CHALLENGE_COOLDOWN"] = ACHAIN_OWNER_CHALLENGE_COOLDOWN;
   result["ACHAIN_OWNER_CHALLENGE_FEE"] = ACHAIN_OWNER_CHALLENGE_FEE;
   result["ACHAIN_OWNER_UPDATE_LIMIT"] = ACHAIN_OWNER_UPDATE_LIMIT;
   result["ACHAIN_POST_AVERAGE_WINDOW"] = ACHAIN_POST_AVERAGE_WINDOW;
   result["ACHAIN_POST_MAX_BANDWIDTH"] = ACHAIN_POST_MAX_BANDWIDTH;
   result["ACHAIN_POST_REWARD_FUND_NAME"] = ACHAIN_POST_REWARD_FUND_NAME;
   result["ACHAIN_POST_WEIGHT_CONSTANT"] = ACHAIN_POST_WEIGHT_CONSTANT;
   result["ACHAIN_POW_APR_PERCENT"] = ACHAIN_POW_APR_PERCENT;
   result["ACHAIN_PRODUCER_APR_PERCENT"] = ACHAIN_PRODUCER_APR_PERCENT;
   result["ACHAIN_PROXY_TO_SELF_ACCOUNT"] = ACHAIN_PROXY_TO_SELF_ACCOUNT;
   result["ACHAIN_SBD_INTEREST_COMPOUND_INTERVAL_SEC"] = ACHAIN_SBD_INTEREST_COMPOUND_INTERVAL_SEC;
   result["ACHAIN_SECONDS_PER_YEAR"] = ACHAIN_SECONDS_PER_YEAR;
   result["ACHAIN_RECENT_RSHARES_DECAY_RATE_HF19"] = ACHAIN_RECENT_RSHARES_DECAY_RATE_HF19;
   result["ACHAIN_RECENT_RSHARES_DECAY_RATE_HF17"] = ACHAIN_RECENT_RSHARES_DECAY_RATE_HF17;
   result["ACHAIN_REVERSE_AUCTION_WINDOW_SECONDS"] = ACHAIN_REVERSE_AUCTION_WINDOW_SECONDS;
   result["ACHAIN_ROOT_POST_PARENT"] = ACHAIN_ROOT_POST_PARENT;
   result["ACHAIN_SAVINGS_WITHDRAW_REQUEST_LIMIT"] = ACHAIN_SAVINGS_WITHDRAW_REQUEST_LIMIT;
   result["ACHAIN_SAVINGS_WITHDRAW_TIME"] = ACHAIN_SAVINGS_WITHDRAW_TIME;
   result["ACHAIN_SBD_START_PERCENT"] = ACHAIN_SBD_START_PERCENT;
   result["ACHAIN_SBD_STOP_PERCENT"] = ACHAIN_SBD_STOP_PERCENT;
   result["ACHAIN_SECOND_CASHOUT_WINDOW"] = ACHAIN_SECOND_CASHOUT_WINDOW;
   result["ACHAIN_SOFT_MAX_COMMENT_DEPTH"] = ACHAIN_SOFT_MAX_COMMENT_DEPTH;
   result["ACHAIN_START_MINER_VOTING_BLOCK"] = ACHAIN_START_MINER_VOTING_BLOCK;
   result["ACHAIN_START_VESTING_BLOCK"] = ACHAIN_START_VESTING_BLOCK;
   result["ACHAIN_SYMBOL"] = ACHAIN_SYMBOL;
   result["ACHAIN_TEMP_ACCOUNT"] = ACHAIN_TEMP_ACCOUNT;
   result["ACHAIN_UPVOTE_LOCKOUT_HF7"] = ACHAIN_UPVOTE_LOCKOUT_HF7;
   result["ACHAIN_UPVOTE_LOCKOUT_HF17"] = ACHAIN_UPVOTE_LOCKOUT_HF17;
   result["ACHAIN_VESTING_FUND_PERCENT"] = ACHAIN_VESTING_FUND_PERCENT;
   result["ACHAIN_VESTING_WITHDRAW_INTERVALS"] = ACHAIN_VESTING_WITHDRAW_INTERVALS;
   result["ACHAIN_VESTING_WITHDRAW_INTERVALS_PRE_HF_16"] = ACHAIN_VESTING_WITHDRAW_INTERVALS_PRE_HF_16;
   result["ACHAIN_VESTING_WITHDRAW_INTERVAL_SECONDS"] = ACHAIN_VESTING_WITHDRAW_INTERVAL_SECONDS;
   result["ACHAIN_VOTE_CHANGE_LOCKOUT_PERIOD"] = ACHAIN_VOTE_CHANGE_LOCKOUT_PERIOD;
   result["ACHAIN_VOTE_DUST_THRESHOLD"] = ACHAIN_VOTE_DUST_THRESHOLD;
   result["ACHAIN_VOTE_REGENERATION_SECONDS"] = ACHAIN_VOTE_REGENERATION_SECONDS;
   result["STEEM_SYMBOL"] = STEEM_SYMBOL;
   result["STMD_SYMBOL"] = STMD_SYMBOL;
   result["VESTS_SYMBOL"] = VESTS_SYMBOL;
   result["VIRTUAL_SCHEDULE_LAP_LENGTH"] = VIRTUAL_SCHEDULE_LAP_LENGTH;
   result["VIRTUAL_SCHEDULE_LAP_LENGTH2"] = VIRTUAL_SCHEDULE_LAP_LENGTH2;

   return result;
}

} } // achain::protocol
